// Auto-generated by scripts/match_icons.js
export interface BrandInfo {
  color: string;
  slug: string;
  iconName: string;
}

export const brandData: Record<string, BrandInfo> = {
  "Netflix": {
    "color": "#E50914",
    "slug": "netflix",
    "iconName": "SiNetflix"
  },
  "Spotify": {
    "color": "#1ED760",
    "slug": "spotify",
    "iconName": "SiSpotify"
  },
  "iCloud+": {
    "color": "#000000",
    "slug": "apple",
    "iconName": "SiApple"
  },
  "Google One": {
    "color": "#4285F4",
    "slug": "google",
    "iconName": "SiGoogle"
  },
  "YouTube Premium": {
    "color": "#FF0000",
    "slug": "youtube",
    "iconName": "SiYoutube"
  },
  "Apple Music": {
    "color": "#000000",
    "slug": "apple",
    "iconName": "SiApple"
  },
  "PlayStation Plus": {
    "color": "#0070D1",
    "slug": "playstation",
    "iconName": "SiPlaystation"
  },
  "Notion": {
    "color": "#000000",
    "slug": "notion",
    "iconName": "SiNotion"
  },
  "Tinder Gold": {
    "color": "#FF6B6B",
    "slug": "tinder",
    "iconName": "SiTinder"
  },
  "Crunchyroll": {
    "color": "#FF5E00",
    "slug": "crunchyroll",
    "iconName": "SiCrunchyroll"
  },
  "Paramount+": {
    "color": "#0064FF",
    "slug": "paramountplus",
    "iconName": "SiParamountplus"
  },
  "HBO Max": {
    "color": "#000000",
    "slug": "hbomax",
    "iconName": "SiHbomax"
  },
  "Apple TV+": {
    "color": "#000000",
    "slug": "apple",
    "iconName": "SiApple"
  },
  "Audible": {
    "color": "#F8991C",
    "slug": "audible",
    "iconName": "SiAudible"
  },
  "L'Équipe": {
    "color": "#E42829",
    "slug": "lequipe",
    "iconName": "SiLequipe"
  },
  "Strava": {
    "color": "#FC4C02",
    "slug": "strava",
    "iconName": "SiStrava"
  },
  "Headspace": {
    "color": "#F47D31",
    "slug": "headspace",
    "iconName": "SiHeadspace"
  },
  "Peloton": {
    "color": "#181A1D",
    "slug": "peloton",
    "iconName": "SiPeloton"
  },
  "HelloFresh": {
    "color": "#99CC33",
    "slug": "hellofresh",
    "iconName": "SiHellofresh"
  },
  "NordVPN": {
    "color": "#4687FF",
    "slug": "nordvpn",
    "iconName": "SiNordvpn"
  },
  "ExpressVPN": {
    "color": "#DA3940",
    "slug": "expressvpn",
    "iconName": "SiExpressvpn"
  },
  "Dashlane": {
    "color": "#0E353D",
    "slug": "dashlane",
    "iconName": "SiDashlane"
  },
  "1Password": {
    "color": "#3B66BC",
    "slug": "1password",
    "iconName": "Si1password"
  },
  "Dropbox": {
    "color": "#0061FF",
    "slug": "dropbox",
    "iconName": "SiDropbox"
  },
  "Zoom Pro": {
    "color": "#0B5CFF",
    "slug": "zoom",
    "iconName": "SiZoom"
  },
  "Duolingo Plus": {
    "color": "#58CC02",
    "slug": "duolingo",
    "iconName": "SiDuolingo"
  },
  "Uber One": {
    "color": "#000000",
    "slug": "uber",
    "iconName": "SiUber"
  },
  "Deliveroo Plus": {
    "color": "#00CCBC",
    "slug": "deliveroo",
    "iconName": "SiDeliveroo"
  },
  "SNCF Connect Max": {
    "color": "#CA0939",
    "slug": "sncf",
    "iconName": "SiSncf"
  },
  "Orange Fibre": {
    "color": "#FF7900",
    "slug": "orange",
    "iconName": "SiOrange"
  },
  "Claude Pro": {
    "color": "#191919",
    "slug": "anthropic",
    "iconName": "SiAnthropic"
  },
  "Github Copilot": {
    "color": "#181717",
    "slug": "github",
    "iconName": "SiGithub"
  },
  "Vercel Pro": {
    "color": "#000000",
    "slug": "vercel",
    "iconName": "SiVercel"
  },
  "DigitalOcean": {
    "color": "#0080FF",
    "slug": "digitalocean",
    "iconName": "SiDigitalocean"
  },
  "Shopify": {
    "color": "#7AB55C",
    "slug": "shopify",
    "iconName": "SiShopify"
  },
  "Squarespace": {
    "color": "#000000",
    "slug": "squarespace",
    "iconName": "SiSquarespace"
  },
  "Wix": {
    "color": "#0C6EFC",
    "slug": "wix",
    "iconName": "SiWix"
  },
  "Mailchimp": {
    "color": "#FFE01B",
    "slug": "mailchimp",
    "iconName": "SiMailchimp"
  },
  "Zapier": {
    "color": "#FF4F00",
    "slug": "zapier",
    "iconName": "SiZapier"
  },
  "Grammarly": {
    "color": "#027E6F",
    "slug": "grammarly",
    "iconName": "SiGrammarly"
  },
  "Twitch Sub": {
    "color": "#9146FF",
    "slug": "twitch",
    "iconName": "SiTwitch"
  },
  "Discord Nitro": {
    "color": "#5865F2",
    "slug": "discord",
    "iconName": "SiDiscord"
  },
  "Snapchat+": {
    "color": "#FFFC00",
    "slug": "snapchat",
    "iconName": "SiSnapchat"
  },
  "X Premium": {
    "color": "#000000",
    "slug": "x",
    "iconName": "SiX"
  },
  "Skillshare": {
    "color": "#00FF84",
    "slug": "skillshare",
    "iconName": "SiSkillshare"
  },
  "Coursera Plus": {
    "color": "#0056D2",
    "slug": "coursera",
    "iconName": "SiCoursera"
  },
  "Udacity": {
    "color": "#02B3E4",
    "slug": "udacity",
    "iconName": "SiUdacity"
  },
  "Codecademy Pro": {
    "color": "#1F4056",
    "slug": "codecademy",
    "iconName": "SiCodecademy"
  },
  "DAZN": {
    "color": "#F8F8F5",
    "slug": "dazn",
    "iconName": "SiDazn"
  },
  "Spotify Family": {
    "color": "#1ED760",
    "slug": "spotify",
    "iconName": "SiSpotify"
  },
  "Tidal": {
    "color": "#000000",
    "slug": "tidal",
    "iconName": "SiTidal"
  },
  "SoundCloud Go+": {
    "color": "#FF5500",
    "slug": "soundcloud",
    "iconName": "SiSoundcloud"
  },
  "Evernote": {
    "color": "#00A82D",
    "slug": "evernote",
    "iconName": "SiEvernote"
  },
  "Todoist Pro": {
    "color": "#E44332",
    "slug": "todoist",
    "iconName": "SiTodoist"
  },
  "Asana": {
    "color": "#F06A6A",
    "slug": "asana",
    "iconName": "SiAsana"
  },
  "Jira": {
    "color": "#0052CC",
    "slug": "jira",
    "iconName": "SiJira"
  },
  "Airtable": {
    "color": "#18BFFF",
    "slug": "airtable",
    "iconName": "SiAirtable"
  },
  "HubSpot": {
    "color": "#FF7A59",
    "slug": "hubspot",
    "iconName": "SiHubspot"
  },
  "Intercom": {
    "color": "#6AFDEF",
    "slug": "intercom",
    "iconName": "SiIntercom"
  },
  "Typeform": {
    "color": "#262627",
    "slug": "typeform",
    "iconName": "SiTypeform"
  },
  "SurveyMonkey": {
    "color": "#00BF6F",
    "slug": "surveymonkey",
    "iconName": "SiSurveymonkey"
  },
  "Buffer": {
    "color": "#231F20",
    "slug": "buffer",
    "iconName": "SiBuffer"
  },
  "Hootsuite": {
    "color": "#FF4C46",
    "slug": "hootsuite",
    "iconName": "SiHootsuite"
  },
  "Semrush": {
    "color": "#FF642D",
    "slug": "semrush",
    "iconName": "SiSemrush"
  },
  "TradingView": {
    "color": "#131622",
    "slug": "tradingview",
    "iconName": "SiTradingview"
  },
  "Expensify": {
    "color": "#0185FF",
    "slug": "expensify",
    "iconName": "SiExpensify"
  },
  "QuickBooks": {
    "color": "#2CA01C",
    "slug": "quickbooks",
    "iconName": "SiQuickbooks"
  },
  "Xero": {
    "color": "#13B5EA",
    "slug": "xero",
    "iconName": "SiXero"
  },
  "Patreon": {
    "color": "#000000",
    "slug": "patreon",
    "iconName": "SiPatreon"
  },
  "Substack": {
    "color": "#FF6719",
    "slug": "substack",
    "iconName": "SiSubstack"
  },
  "OnlyFans": {
    "color": "#00AFF0",
    "slug": "onlyfans",
    "iconName": "SiOnlyfans"
  },
  "Gumroad": {
    "color": "#FF90E8",
    "slug": "gumroad",
    "iconName": "SiGumroad"
  },
  "Fnac+": {
    "color": "#E1A925",
    "slug": "fnac",
    "iconName": "SiFnac"
  },
  "Darty Max": {
    "color": "#EB1B23",
    "slug": "darty",
    "iconName": "SiDarty"
  },
  "Instacart+": {
    "color": "#43B02A",
    "slug": "instacart",
    "iconName": "SiInstacart"
  },
  "Uber Eats Pass": {
    "color": "#06C167",
    "slug": "ubereats",
    "iconName": "SiUbereats"
  },
  "Gojek": {
    "color": "#00AA13",
    "slug": "gojek",
    "iconName": "SiGojek"
  },
  "GrabUnlimited": {
    "color": "#00B14F",
    "slug": "grab",
    "iconName": "SiGrab"
  },
  "TripAdvisor Plus": {
    "color": "#34E0A1",
    "slug": "tripadvisor",
    "iconName": "SiTripadvisor"
  },
  "Surfshark": {
    "color": "#1EBFBF",
    "slug": "surfshark",
    "iconName": "SiSurfshark"
  },
  "ProtonMail": {
    "color": "#6D4AFF",
    "slug": "protonmail",
    "iconName": "SiProtonmail"
  },
  "LastPass": {
    "color": "#D32D27",
    "slug": "lastpass",
    "iconName": "SiLastpass"
  },
  "Bitwarden": {
    "color": "#175DDC",
    "slug": "bitwarden",
    "iconName": "SiBitwarden"
  },
  "Malwarebytes": {
    "color": "#0D3ECC",
    "slug": "malwarebytes",
    "iconName": "SiMalwarebytes"
  },
  "Bitdefender": {
    "color": "#ED1C24",
    "slug": "bitdefender",
    "iconName": "SiBitdefender"
  },
  "McAfee": {
    "color": "#C01818",
    "slug": "mcafee",
    "iconName": "SiMcafee"
  },
  "Norton": {
    "color": "#FFE01A",
    "slug": "norton",
    "iconName": "SiNorton"
  },
  "Vivint": {
    "color": "#212721",
    "slug": "vivint",
    "iconName": "SiVivint"
  },
  "Roku Premium": {
    "color": "#662D91",
    "slug": "roku",
    "iconName": "SiRoku"
  },
  "Mubi": {
    "color": "#000000",
    "slug": "mubi",
    "iconName": "SiMubi"
  },
  "Nebula": {
    "color": "#2CADFE",
    "slug": "nebula",
    "iconName": "SiNebula"
  },
  "Floatplane": {
    "color": "#00AEEF",
    "slug": "floatplane",
    "iconName": "SiFloatplane"
  },
  "Chess.com Premium": {
    "color": "#81B64C",
    "slug": "chessdotcom",
    "iconName": "SiChessdotcom"
  },
  "Roblox Premium": {
    "color": "#000000",
    "slug": "roblox",
    "iconName": "SiRoblox"
  },
  "Ubisoft+": {
    "color": "#000000",
    "slug": "ubisoft",
    "iconName": "SiUbisoft"
  },
  "Apple Arcade": {
    "color": "#000000",
    "slug": "applearcade",
    "iconName": "SiApplearcade"
  },
  "Google Play Pass": {
    "color": "#414141",
    "slug": "googleplay",
    "iconName": "SiGoogleplay"
  },
  "Bilibili": {
    "color": "#00A1D6",
    "slug": "bilibili",
    "iconName": "SiBilibili"
  },
  "Starz": {
    "color": "#082125",
    "slug": "starz",
    "iconName": "SiStarz"
  },
  "Showtime": {
    "color": "#B10000",
    "slug": "showtime",
    "iconName": "SiShowtime"
  },
  "Fitbit Premium": {
    "color": "#00B0B9",
    "slug": "fitbit",
    "iconName": "SiFitbit"
  },
  "Komoot": {
    "color": "#6AA127",
    "slug": "komoot",
    "iconName": "SiKomoot"
  },
  "AllTrails+": {
    "color": "#142800",
    "slug": "alltrails",
    "iconName": "SiAlltrails"
  },
  "Geocaching Premium": {
    "color": "#00874D",
    "slug": "geocaching",
    "iconName": "SiGeocaching"
  },
  "Quizlet Plus": {
    "color": "#4255FF",
    "slug": "quizlet",
    "iconName": "SiQuizlet"
  },
  "Pocket Casts Plus": {
    "color": "#F43E37",
    "slug": "pocketcasts",
    "iconName": "SiPocketcasts"
  },
  "Overcast Premium": {
    "color": "#FC7E0F",
    "slug": "overcast",
    "iconName": "SiOvercast"
  },
  "Castro Plus": {
    "color": "#00B265",
    "slug": "castro",
    "iconName": "SiCastro"
  },
  "Instapaper Premium": {
    "color": "#1F1F1F",
    "slug": "instapaper",
    "iconName": "SiInstapaper"
  },
  "Feedly Pro": {
    "color": "#2BB24C",
    "slug": "feedly",
    "iconName": "SiFeedly"
  },
  "Inoreader Pro": {
    "color": "#1875F3",
    "slug": "inoreader",
    "iconName": "SiInoreader"
  },
  "Loom Pro": {
    "color": "#625DF5",
    "slug": "loom",
    "iconName": "SiLoom"
  },
  "Calendly Pro": {
    "color": "#006BFF",
    "slug": "calendly",
    "iconName": "SiCalendly"
  },
  "Miro Pro": {
    "color": "#050038",
    "slug": "miro",
    "iconName": "SiMiro"
  },
  "Marvel App": {
    "color": "#1FB6FF",
    "slug": "marvelapp",
    "iconName": "SiMarvelapp"
  },
  "Sketch": {
    "color": "#F7B500",
    "slug": "sketch",
    "iconName": "SiSketch"
  },
  "Pixlr Premium": {
    "color": "#3EBBDF",
    "slug": "pixlr",
    "iconName": "SiPixlr"
  },
  "VSCO Membership": {
    "color": "#000000",
    "slug": "vsco",
    "iconName": "SiVsco"
  },
  "Ghost Pro": {
    "color": "#15171A",
    "slug": "ghost",
    "iconName": "SiGhost"
  },
  "Medium Membership": {
    "color": "#000000",
    "slug": "medium",
    "iconName": "SiMedium"
  },
  "GoDaddy": {
    "color": "#1BDBDB",
    "slug": "godaddy",
    "iconName": "SiGodaddy"
  },
  "Namecheap": {
    "color": "#DE3723",
    "slug": "namecheap",
    "iconName": "SiNamecheap"
  },
  "Cloudways": {
    "color": "#2C39BD",
    "slug": "cloudways",
    "iconName": "SiCloudways"
  },
  "Netlify Pro": {
    "color": "#00C7B7",
    "slug": "netlify",
    "iconName": "SiNetlify"
  },
  "Supabase Pro": {
    "color": "#3FCF8E",
    "slug": "supabase",
    "iconName": "SiSupabase"
  },
  "PlanetScale": {
    "color": "#000000",
    "slug": "planetscale",
    "iconName": "SiPlanetscale"
  },
  "Fly.io": {
    "color": "#24175B",
    "slug": "flydotio",
    "iconName": "SiFlydotio"
  },
  "Monzo Plus": {
    "color": "#14233C",
    "slug": "monzo",
    "iconName": "SiMonzo"
  },
  "Brex": {
    "color": "#212121",
    "slug": "brex",
    "iconName": "SiBrex"
  },
  "OnStar": {
    "color": "#003D7D",
    "slug": "onstar",
    "iconName": "SiOnstar"
  },
  "Audi connect": {
    "color": "#BB0A30",
    "slug": "audi",
    "iconName": "SiAudi"
  },
  "FordPass Connect": {
    "color": "#00274E",
    "slug": "ford",
    "iconName": "SiFord"
  },
  "Kia Connect": {
    "color": "#05141F",
    "slug": "kia",
    "iconName": "SiKia"
  },
  "National Grid": {
    "color": "#00148C",
    "slug": "nationalgrid",
    "iconName": "SiNationalgrid"
  },
  "Billboard": {
    "color": "#000000",
    "slug": "billboard",
    "iconName": "SiBillboard"
  },
  "Ko-fi Gold": {
    "color": "#FF6433",
    "slug": "kofi",
    "iconName": "SiKofi"
  },
  "Buy Me a Coffee": {
    "color": "#FFDD00",
    "slug": "buymeacoffee",
    "iconName": "SiBuymeacoffee"
  },
  "Liberapay": {
    "color": "#F6C915",
    "slug": "liberapay",
    "iconName": "SiLiberapay"
  },
  "Open Collective": {
    "color": "#7FADF2",
    "slug": "opencollective",
    "iconName": "SiOpencollective"
  },
  "GitHub Sponsors": {
    "color": "#EA4AAA",
    "slug": "githubsponsors",
    "iconName": "SiGithubsponsors"
  }
};
